name: Node.js CI

on:
  push:
    branches: [ "develop", "teste-1" ]
  pull_request:
    branches: [ "develop", "teste-1" ]

jobs:
  ci:
    runs-on: woof-runner
    outputs:
      atual: ${{ steps.ci-app.outputs.atual }}
    steps:
      - name: Criar Work
        run: |
          mkdir ${{ github.sha }}
          cd ${{ github.sha }}
      
      - name: Clone Repositório
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.X
          cache: 'npm'
      
      - name: CI APP
        id: ci-app
        run: |
          sudo npm install --force
          sudo npm run build
          export atual=$(pwd)
          cd /var/www/html/
          # sudo rm -r *
          cd $atual/build
          sudo cp -r * /var/www/html/

  cd:
    needs: [ci]
    runs-on: woof-runner
    steps:
      - name: CD APP
        run: |
          
          sudo systemctl restart nginx 
